# Generated by Django 5.2.6 on 2025-11-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'ordering': ['-hobby']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
