# Generated by Django 5.2.6 on 2025-11-12 09:13

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_hobbies_options_user_is_subscribed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='distance',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goal',
            field=models.CharField(blank=True, choices=[('love', 'Love'), ('friendship', 'Friendship'), ('networking', 'Networking')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='hoping_to_find',
            field=models.CharField(blank=True, choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-binary')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('long_term_relationship', 'Long-term Relationship'), ('life_partner', 'Life Partner'), ('fun_casual_dating', 'Fun/Casual Dating'), ('intimacy', 'Intimacy without commitment'), ('marriage', 'Marriage'), ('ethical_non_monogamy', 'Ethical Non-monogamy')], max_length=50, null=True),
        ),
    ]
