# Generated by Django 5.2.6 on 2025-11-13 08:06

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_makeyourprofilepop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makeyourprofilepop',
            name='image',
            field=models.ImageField(upload_to='user_pop_images/', validators=[account.utils.validate_image]),
        ),
    ]
