# Generated by Django 5.2.6 on 2025-11-15 04:15

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('long_term_relationship', 'A long- term relationship'), ('life_partner', 'A life partner'), ('fun_casual_dating', 'Fun, casual dates'), ('intimacy', 'Intimacy, without commitment'), ('marriage', 'Marriage'), ('ethical_non_monogamy', 'Ethical non-monogamy')], max_length=50, null=True),
        ),
    ]
