# Generated by Django 5.2.6 on 2025-11-15 04:48

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_looking_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='looking_for',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('A long- term relationship', 'A long- term relationship'), ('A life partner', 'A life partner'), ('Fun, casual dates', 'Fun, casual dates'), ('intimaIntimacy, without commitmentcy', 'Intimacy, without commitment'), ('Marriage', 'Marriage'), ('Ethical non-monogamy', 'Ethical non-monogamy')], max_length=50, null=True),
        ),
    ]
