# Generated by Django 5.2.6 on 2025-11-16 11:47

import account.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='hobby_icons/', validators=[account.utils.validate_image]),
        ),
    ]
