# Generated by Django 5.2.6 on 2025-11-16 12:26

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_looking_for'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobbies',
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('R&B', 'R&B'), ('Gardening', 'Gardening'), ('LGBTQ & Rights', 'LGBTQ & Rights'), ('Vegetarian', 'Vegetarian'), ('Dancing', 'Dancing'), ('Dogs', 'Dogs'), ('Museums & galleries', 'Museums & galleries'), ('Wine', 'Wine'), ('Writing', 'Writing'), ('Yoga', 'Yoga'), ('Baking', 'Baking')], max_length=50, null=True),
        ),
    ]
