# Generated by Django 5.2.6 on 2026-03-01 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0002_remove_usersubscription_plan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('premium_plus', 'Premium Plus')], max_length=20)),
                ('duration_days', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('features', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenuecat_subscriber_id', models.CharField(max_length=255, unique=True)),
                ('original_transaction_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('trial', 'Trial'), ('grace_period', 'Grace Period')], default='expired', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('will_renew', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('is_trial', models.BooleanField(default=False)),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_expires_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionplan')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('initial_purchase', 'Initial Purchase'), ('renewal', 'Renewal'), ('cancellation', 'Cancellation'), ('reactivation', 'Reactivation'), ('expiration', 'Expiration'), ('refund', 'Refund'), ('trial_started', 'Trial Started'), ('trial_converted', 'Trial Converted'), ('billing_issue', 'Billing Issue')], max_length=30)),
                ('event_timestamp', models.DateTimeField()),
                ('revenuecat_event_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('transaction_id', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='subscription.usersubscription')),
            ],
            options={
                'ordering': ['-event_timestamp'],
                'indexes': [models.Index(fields=['user_subscription', '-event_timestamp'], name='subscriptio_user_su_ccb90b_idx')],
            },
        ),
    ]
