# Generated by Django 5.2.6 on 2025-11-16 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0003_userblock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('fake_profile', 'Profile is fake'), ('inappropriate_messages', 'Inappropriate messages'), ('harassment', 'Harassment or bullying'), ('offensive_content', 'Offensive content'), ('technical_problem', 'Technical problem'), ('other', 'Other')], max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['reported_user'], name='mutual_syst_reporte_cdac35_idx'), models.Index(fields=['reporter'], name='mutual_syst_reporte_298632_idx'), models.Index(fields=['reported_user', 'created_at'], name='mutual_syst_reporte_d114e1_idx')],
            },
        ),
    ]
