# Generated by Django 5.2.6 on 2025-11-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0004_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('Profile is fake', 'Profile is fake'), ('Inappropriate messages', 'Inappropriate messages'), ('Harassment or bullying', 'Harassment or bullying'), ('Offensive content', 'Offensive content'), ('Technical problem', 'Technical problem'), ('Other', 'Other')], max_length=50),
        ),
    ]
