# Generated by Django 5.2.6 on 2025-11-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0006_storylike'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='storylike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storylike',
            index=models.Index(fields=['story', 'user'], name='mutual_syst_story_i_f68d88_idx'),
        ),
    ]
