# Generated by Django 5.2.6 on 2025-11-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0007_alter_storylike_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
