# Generated by Django 5.2.6 on 2025-11-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutual_system', '0008_story_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(choices=[('Profile is fake', 'Profile is fake'), ('Inappropriate messages', 'Inappropriate messages'), ('Harassment or bullying', 'Harassment or bullying'), ('Offensive content', 'Offensive content'), ('Technical problem', 'Technical problem'), ('Other issues', 'Other issues')], max_length=50),
        ),
    ]
